# 启用debug模式
# debug: true

# ANSI颜色编码，支持值：always、detect、never
# always：启用 ANSI 彩色输出
# detect：尝试检测 ANSI 着色功能是否可用（默认）
# never：禁用 ANSI 彩色输出
spring:
  output:
    ansi:
      enabled: detect
  application:
    name: spring-boot-logging
  profiles:
    active: dev
#logging:
#  file: /Users/fulgens/Downloads/my.log
#  path: /var/log
